OPEN_SKY_ENDPOINT = "https://opensky-network.org/api/"
ARRIVAL_AIRPORT = "flights/arrival"
FLIGHTS_AIRCRAFT = "flights/aircraft"
FLIGHTS_DEPARTURE = "flights/departure"
ALL_STATE_VECTORS = "states/all"
OWN_STATE_VECTORS = "states/own"
