openapi: 3.0.0
info:
  version: 0.0.2
  title: Test title
  description: Test description
paths:
    /api/airport:
        get:
            tags:
                - Airport
            summary: Endpoint returning a list of 1000 airports.
            responses:
                200:
                    description: A list of 1000 airports.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Airport'

    /api/country/{records}:
        get:
            tags:
                - Country
            summary: Endpoint returing a list of countries.
            parameters:
                - in: path
                  name: records
                  schema:
                      type: integer
                  required: false
                  description: Number of records to be returned.
            responses:
                200:
                    description: A list of countries.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Country'

    /api/country/short-name/{short_name}/{records}:
        get:
            tags:
                - Country
            summary: Endpoint returning a list of countries matching the `short_name` parameter.
            parameters:
                - in: path
                  name: short_name
                  schema:
                      type: string
                  required: true
                  description: Acronym of country to be searched.
                - in: path
                  name: records
                  schema:
                      type: integer
                  required: false
                  description: Number of records to be returned.
            responses:
                200:
                    description: A list of countries matching criteria.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Country'

    /api/country/long-name/{long_name}/{records}:
        get:
            tags:
                - Country
            summary: Endpoint returning a list of countries matching the `long_name` parameter.
            parameters:
                - in: path
                  name: long_name
                  schema:
                      type: string
                  required: true
                  description: String of country to be searched.
                - in: path
                  name: records
                  schema:
                      type: integer
                  required: false
                  description: Number of records to be returned.
            responses:
                200:
                    description: A list of countries matching criteria.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Country'

components:
    schemas:
        Airport:
            type: object
            properties:
                name:
                    type: string
                    description: Name of the airport
                icao:
                    type: string
                    description: Unique ICAO code for the airport
                iata:
                    type: string
                    description: Unique IATA code for the airport
                location:
                    type: string
                    description: Nearest location of the airport. Could be city or village
                latitude:
                    type: number
                    description: Latitude of the airport
                longitude:
                    type: number
                    description: Longitude of the airport

        Country:
            type: object
            properties:
                long_name:
                    type: string
                    description: Long name of a country
                short_name:
                    type: string
                    description: Acronym of a country
